title: Maxime BALLESTEROS PEREZ # your name (or website title) here
logo: "/Users/MaxiPunKey/Desktop/DOCS IMPORTANT/PERSO/profile-job.jpeg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Student @emlyon business school
  <br>
  Msc In Digital Marketing & Data Science
  <br><br>
  Engineering degree in Computer Science @ESIEE Paris
  <br>
  Former Programmer Analyst @RCI Bank & Services
  <br><br>
  <a href="https://www.linkedin.com/in/maxime-ballesteros-perez-7604b113b/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
